version: "3"
services:
  mysql-5.5:
    image: "mysql:5.5"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    healthcheck:
      test: "mysql -e 'SELECT @@version;'"
      interval: 5s
      timeout: 5s
      retries: 5
