version: "3"
services:
  mysql-5.5:
    image: "mysql:5.5"
    ports:
      - "5050:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    options: >-
      --health-cmd "mysql -e 'SELECT @@version;'"
      --health-interval 5s
      --health-timeout 5s
      --health-retries 5
