name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: hexpm/elixir:1.10.4-erlang-23.0.3-ubuntu-xenial-20200619
    strategy:
      fail-fast: false
      matrix:
        include:
          - db: mysql:5.5
          - db: mysql:5.6
          - db: mysql:5.7
          - db: mysql:8.0
    services:
      mysql:
        image: ${{matrix.db}}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2.3.1
    - run: apt-get install -y mysql-client
    - run: until mysql -u root --host mysql --protocol=tcp -e "SELECT @@version;"; do sleep 1; done
    - run: elixir --version
