name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - db: mysql:5.5
          # - db: mysql:5.6
          # - db: mysql:5.7
          - db: mysql:8.0
    services:
      mysql:
        image: "${{matrix.db}} --innodb_log_file_size=1G"
        options: >-
          --health-cmd "mysql -e 'SELECT @@version;'"
          --health-interval 5s
          --health-timeout 1s
          --health-retries 5
    steps:
    # - run: sudo mkdir -p /var/run/mysqld
    # - run: sudo chmod 777 /var/run/mysqld
    # - run: docker run -p 3306:3306 --volume /var/run/mysqld:/var/run/mysqld -e MYSQL_ALLOW_EMPTY_PASSWORD=1 --detach ${{matrix.db}} --innodb_log_file_size=1G
    # - run: until mysql --port 3306 --protocol=tcp -u root -e "SELECT @@version;"; do sleep 3; done
    # - run: mysql --version
    - run: mysql -u root --protocol tcp -e "status;"
    # - run: mysql -u root -e 'status;'
