name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - db: mysql:5.5
          - db: mysql:5.6
          - db: mysql:5.7
          - db: mysql:8.0
    services:
      mysql:
        image: ${{matrix.db}}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2.3.1
    - run: until mysql -u root --protocol=tcp -e "SELECT @@version;"; do sleep 1; done
